name: build
on:
  pull_request:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-gems-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn check
